

export default `
query getEventFromPrimaryKey($eventId: String!) {
    Event_by_pk(id: $eventId) {
      allDay
      anyoneCanAddSelf
      attachments
      attendeesOmitted
      backgroundColor
      calendarId
      colorId
      conferenceId
      copyAvailability
      copyCategories
      copyDuration
      copyIsBreak
      copyIsExternalMeeting
      copyIsMeeting
      copyModifiable
      copyPriorityLevel
      copyReminders
      copyTimeBlocking
      copyTimePreference
      createdDate
      creator
      dailyTaskList
      deleted
      duration
      endDate
      endTimeUnspecified
      eventId
      eventType
      extendedProperties
      followUpEventId
      forEventId
      foregroundColor
      guestsCanInviteOthers
      guestsCanModify
      guestsCanSeeOtherGuests
      hangoutLink
      hardDeadline
      htmlLink
      iCalUID
      id
      isBreak
      isExternalMeeting
      isExternalMeetingModifiable
      isFollowUp
      isMeeting
      isMeetingModifiable
      isPostEvent
      isPreEvent
      links
      location
      locked
      maxAttendees
      method
      modifiable
      negativeImpactDayOfWeek
      negativeImpactScore
      negativeImpactTime
      notes
      organizer
      originalAllDay
      originalStartDate
      originalTimezone
      positiveImpactDayOfWeek
      positiveImpactScore
      positiveImpactTime
      postEventId
      preEventId
      preferredDayOfWeek
      preferredEndTimeRange
      preferredStartTimeRange
      preferredTime
      priority
      privateCopy
      recurrence
      recurrenceRule
      recurringEventId
      sendUpdates
      softDeadline
      source
      startDate
      status
      summary
      taskId
      taskType
      timeBlocking
      timezone
      title
      transparency
      unlink
      updatedAt
      useDefaultAlarms
      userId
      userModifiedAvailability
      userModifiedCategories
      userModifiedDuration
      userModifiedIsBreak
      userModifiedIsExternalMeeting
      userModifiedIsMeeting
      userModifiedModifiable
      userModifiedPriorityLevel
      userModifiedReminders
      userModifiedTimeBlocking
      userModifiedTimePreference
      visibility
      weeklyTaskList
      byWeekDay
      localSynced
      userModifiedColor
      copyColor
      meetingId
      copyExternalMeetingModifiable
      copyMeetingModifiable
      userModifiedExternalMeetingModifiable
      userModifiedMeetingModifiable
    }
  }          
`