import DateTimeJSONType from '@chat/_libs/datetime/DateTimeJSONJSONType';
import UserInputToJSONType from '@chat/_libs/types/UserInputToJSONType';
import { CreateEventType } from './types';
import OpenAI from 'openai';
import { SkillMessageHistoryType } from '@chat/_libs/types/Messaging/MessagingTypes';
import { ChatMeetingPreferencesType } from '@chat/_libs/types/ChatMeetingPreferencesType';
import ResponseActionType from '@chat/_libs/types/ResponseActionType';
export declare const finalStepCreatEvent: (body: CreateEventType, timezone: string, defaultMeetingPreferences: ChatMeetingPreferencesType, response: any) => Promise<ResponseActionType>;
export declare const processCreateEventPending: (userId: string, timezone: string, jsonBody: UserInputToJSONType, dateJSONBody: DateTimeJSONType, currentTime: string) => Promise<ResponseActionType>;
export declare const processCreateEventMissingFieldsReturned: (userId: string, timezone: string, jsonBody: UserInputToJSONType, dateJSONBody: DateTimeJSONType, currentTime: string, messageHistoryObject: SkillMessageHistoryType) => Promise<any>;
export declare const createEventControlCenter: (openai: OpenAI, userId: string, timezone: string, messageHistoryObject: SkillMessageHistoryType, userCurrentTime: string, query: "missing_fields" | "completed" | "event_not_found" | "pending") => Promise<any>;
