export declare const hasuraGraphUrl: string | undefined;
export declare const hasuraAdminSecret: string | undefined;
export declare const authApiToken: string | undefined;
export declare const dayOfWeekIntToString: {
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
};
export declare const optaPlannerUrl: string | undefined;
export declare const optaPlannerUsername: string | undefined;
export declare const optaPlannerPassword: string | undefined;
export declare const optaplannerDuration: number;
export declare const onOptaPlanCalendarAdminCallBackUrl: string | undefined;
export declare const defaultFreemiumUsage = 5;
export declare const text2VectorUrl: string | undefined;
export declare const openSearchEndPoint: string | undefined;
export declare const eventVectorName = "event-vector";
export declare const vectorDimensions = 384;
export declare const searchIndex = "knn-events-index";
export declare const classificationUrl: string | undefined;
export declare const minThresholdScore = 0.6;
export declare const externalMeetingLabel = "External Meeting";
export declare const meetingLabel = "Meeting";
export declare const googleCalendarResource = "google";
export declare const googleClientIdIos: string | undefined;
export declare const googleClientIdAndroid: string | undefined;
export declare const googleClientIdWeb: string | undefined;
export declare const googleTokenUrl = "https://oauth2.googleapis.com/token";
export declare const googleClientSecretWeb: string | undefined;
export declare const zoomResourceName = "zoom";
export declare const zoomClientSecret: string | undefined;
export declare const zoomClientId: string | undefined;
export declare const zoomTokenUrl = "https://zoom.us/oauth/token";
export declare const zoomBaseUrl = "https://api.zoom.us/v2";
export declare const zoomBaseTokenUrl = "https://zoom.us";
export declare const zoomSaltForPass: string | undefined;
export declare const zoomIVForPass: string | undefined;
export declare const zoomPassKey: string | undefined;
export declare const googleClientIdAtomicWeb: string | undefined;
export declare const googleClientSecretAtomicWeb: string | undefined;
export declare const bucketName: string | undefined;
export declare const kafkaPostProcessCalTopic = "post-process-cal-worker";
export declare const kafkaPostProcessCalGroupId = "post-process-cal";
