module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: 'react-native-dotenv',
        allowUndefined: false,
      },
    ],
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
          '.svg',
          '.png',
          '.ttf',
        ],
        alias: {
          '@assets': './src/assets',
          '@assets/fonts': './src/assets/fonts',
          '@assets/icons': './src/assets/icons',
          '@assets/icons/smiley': './src/assets/icons/smiley',
          '@assets/icons/social': './src/assets/icons/social',
          '@assets/images': './src/assets/images',
          '@screens': './src/Screens',
          '@screens/Goal': './src/Screens/Goal',
          '@screens/Notification': './src/Screens/Notification',
          '@screens/Playback': './src/Screens/Playback',
          '@screens/Schedule': './src/Screens/Schedule',
          '@screens/Settings': './src/Screens/Settings',
          '@screens/User/Login': './src/Screens/Login',
          '@screens/User/Register': './src/Screens/User/Register',
          '@components': './src/components',
          '@components/common': './src/components/common',
          '@navigation': './src/Screens/Navigation',
          '@progress': './src/Screens/Progress',
          '@progress/Exercise': './src/Screens/Progress/Exericse',
          '@progress/Fruit': './src/Screens/Progress/Fruit',
          '@progress/Habit': './src/Screens/Progress/Habit',
          '@progress/Limit': './src/Screens/Progress/Limit',
          '@progress/Meditation': './src/Screens/Progress/Meditation',
          '@progress/NewSkill': './src/Screens/Progress/NewSkill',
          '@progress/Routine': './src/Screens/Progress/Routine',
          '@progress/Sleep': './src/Screens/Progress/Sleep',
          '@progress/Steps': './src/Screens/Progress/Steps',
          '@profile': './src/Screens/Profile',
          '@progress/Strength': './src/Screens/Progress/Strength',
          '@progress/Todo': './src/Screens/Progress/Todo',
          '@progress/Vegetable': './src/Screens/Progress/Vegetable',
          '@progress/Waist': './src/Screens/Progress/Waist',
          '@progress/Water': './src/Screens/Progress/Water',
          '@progress/Weight': './src/Screens/Progress/Weight',
          '@post': './src/Screens/Post',
          '@graphql': './src/graphql',
          '@models': './src/models',
          '@realm': './src/realm',
          '@dataTypes': './src/dataTypes',
          '@theme': './src/theme',
          '@types': './src/types/types',
          '@utils': './src/utils',
          '@constants': './src/constants',
          '@app': './src',
          'pouchdb-md5': 'react-native-pouchdb-md5',
          'pouchdb-binary-utils':
            '@craftzdog/pouchdb-binary-utils-react-native',
        },
      },
    ],
    '@babel/plugin-transform-runtime',
    'react-native-reanimated/plugin',
  ],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
};
