import * as React from 'react';
declare function IconNextChat({ className, inverted, ...props }: React.ComponentProps<'svg'> & {
    inverted?: boolean;
}): JSX.Element;
declare function IconOpenAI({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconVercel({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconGitHub({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconSeparator({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconArrowDown({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconArrowRight({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconUser({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconPlus({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconArrowElbow({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconSpinner({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconMessage({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconTrash({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconRefresh({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconStop({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconSidebar({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconMoon({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconSun({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconCopy({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconCheck({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconDownload({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconClose({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconEdit({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconShare({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconUsers({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconExternalLink({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
declare function IconChevronUpDown({ className, ...props }: React.ComponentProps<'svg'>): JSX.Element;
export { IconEdit, IconNextChat, IconOpenAI, IconVercel, IconGitHub, IconSeparator, IconArrowDown, IconArrowRight, IconUser, IconPlus, IconArrowElbow, IconSpinner, IconMessage, IconTrash, IconRefresh, IconStop, IconSidebar, IconMoon, IconSun, IconCopy, IconCheck, IconDownload, IconClose, IconShare, IconUsers, IconExternalLink, IconChevronUpDown };
