export declare const hasuraGraphUrl: string | undefined;
export declare const hasuraAdminSecret: string | undefined;
export declare const authApiToken: string | undefined;
export declare const openSearchEndPoint: string | undefined;
export declare const eventVectorName = "event-vector";
export declare const eventVectorDimensions = 384;
export declare const eventSearchIndex = "knn-events-index";
export declare const openAIPassKey: string | undefined;
export declare const defaultOpenAIAPIKey: string | undefined;
export declare const emailKnwIndex = "knn-knw-index";
export declare const emailKnwVectorDimensions = 1536;
export declare const emailKnwVectorName = "embeddings";
export declare const openAIChatGPTModel = "gpt-3.5-turbo";
export declare const agentKnwIndex = "knn-agent-index";
export declare const agentKnwVectorDimensions = 1536;
export declare const agentKnwVectorName = "embeddings";
export declare const openTrainEventVectorName = "embeddings";
export declare const openTrainEventVectorDimensions = 1536;
export declare const openTrainEventIndex = "knn-open-train-event-index";
export declare const openAllEventIndex = "knn-open-all-event-index";
export declare const openAllEventVectorDimensions = 1536;
export declare const openAllEventVectorName = "embeddings";
