export declare const hasuraMetadataUrl: string;
export declare const hasuraGraphUrl: string;
export declare const hasuraAdminSecret: string;
export declare const authApiToken: string;
export declare const text2VectorUrl: string;
export declare const openSearchEndPoint: string;
export declare const eventVectorName = 'event-vector';
export declare const vectorDimensions = 384;
export declare const searchIndex = 'knn-events-index';
export declare const googleCalendarResource = 'google';
export declare const googlePeopleResource = 'google';
export declare const googlePeopleName = 'Google Contacts';
export declare const googleMeetResource = 'google';
export declare const googleClientIdIos: string;
export declare const googleClientIdAndroid: string;
export declare const googleClientIdWeb: string;
export declare const googleTokenUrl = 'https://oauth2.googleapis.com/token';
export declare const googleClientSecretWeb: string;
export declare const googleClientIdAtomicWeb: string;
export declare const zoomResourceName = 'zoom';
export declare const zoomClientSecret: string;
export declare const zoomClientId: string;
export declare const zoomBaseUrl = 'https://api.zoom.us/v2';
export declare const zoomBaseTokenUrl = 'https://zoom.us';
export declare const googleColorUrl =
  'https://www.googleapis.com/calendar/v3/colors';
export declare const selfGoogleCalendarWebhookPublicUrl: string;
export declare const selfGooglePeopleAdminUrl: string;
export declare const zoomSaltForPass: string;
export declare const zoomIVForPass: string;
export declare const zoomPassKey: string;
export declare const googleClientSecretAtomicWeb: string;
export declare const bucketName: string;
export declare const defaultOpenAIAPIKey: string;
export declare const openAllEventIndex = 'knn-open-all-event-index';
export declare const openAllEventVectorDimensions = 1536;
export declare const openAIChatGPT35Model = 'gpt-3.5-turbo';
export declare const openAIChatGPT35LongModel = 'gpt-3.5-turbo-16k';
export declare const openAIChatGPT4Model = 'gpt-4';
export declare const openAllEventVectorName = 'embeddings';
export declare const googleCalendarStopWatchUrl =
  'https://www.googleapis.com/calendar/v3/channels/stop';
export declare const openTrainEventVectorName = 'embeddings';
export declare const openTrainEventVectorDimensions = 1536;
export declare const openTrainEventIndex = 'knn-open-train-event-index';
export declare const kafkaGoogleCalendarSyncTopic = 'google-calendar-sync';
export declare const kafkaGoogleCalendarSyncGroupId = 'google-calendar-sync';
